source/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from rest_framework.routers import SimpleRouter

router = SimpleRouter()

urlpatterns = [
    # Root:

    # Returning Project instances:
    path('project/', views.ProjectList.as_view(), name='project-list'),
    path('project/<int:pk>/', views.ProjectDetail.as_view(), name='project-detail'),

    # Returning Project Statistics instances:
    path('project_statistics/', views.ProjectStatisticsList.as_view(),
         name='project-statistics-list'),
    path('project_statistics/<int:pk>/',
         views.ProjectStatisticsDetail.as_view(), name='project-statistics-detail'),

    # Returning Project Features instances:
    path('project_features/', views.ProjectFeaturesList.as_view(),
         name='project-features-list'),
    path('project_features/<int:pk>/',
         views.ProjectFeaturesDetail.as_view(), name='project-features-detail'),

    # Returning Project TimeSeries instances:
    path('time_series/', views.TimeSeriesList.as_view(), name='time-series-list'),
    path('time_series/<int:pk>/', views.TimeSeriesDetail.as_view(),
         name='time-series-detail'),
    # Root:
    path('', views.api_root)

]

urlpatterns = format_suffix_patterns(urlpatterns)

'''
# Returning Project Statistics instances:

'''

source/openuniverse/urls.py
# Here we have the url general mapping
# Here is where we define the path that the user will request

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]
 
handler404 = 'website.views.handler404'

source/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'), 
    path('search', views.search, name='search'),
    path('explore', views.explore, name='explore'),
    path('overview', views.overview, name='overview'),
    path('<str:owner>/<str:name>', views.project, name='project')
    ]

source/website/models.py
# -*- coding: utf-8 -*-
'''
    The models.py is responsible for defining the
    sources of information available in our database.
    Each class is a table, each variable is a column.
'''
from django.db import models

'''
    The Project model handles basic information of a project.
''' 
class Project(models.Model):
    name = models.TextField()
    owner = models.TextField()
    owner_type = models.TextField()
    updated_at = models.DateTimeField()
    created_at = models.DateTimeField()
    application_domain = models.TextField()
    software_license = models.TextField()
    age = models.IntegerField()
    main_language = models.TextField()
    github_url = models.TextField()

    class Meta:
        verbose_name_plural = "Projects"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

'''
    ProjectStatistics has some important metrics on a project
    It's linked by an on_to_one relation to the Project model
'''
class ProjectStatistics(models.Model):
    project = models.OneToOneField(Project, on_delete=models.CASCADE, primary_key=True)
    pulls_merged_total = models.IntegerField()
    newcomers_total = models.IntegerField()
    open_issues_total = models.IntegerField()
    used_languages_total = models.IntegerField()
    forks_total = models.IntegerField()
    stars_total = models.IntegerField()
    commits_total = models.IntegerField()
    contributors_total = models.IntegerField()
    core_members_total = models.IntegerField()

    class Meta:
        verbose_name_plural = "Projects Statistics"

    def __str__(self):
        return self.project

    def __unicode__(self):
        return self.project

'''
    Some features a projects repository might have
    It's linked by an on_to_one relation to the Project model
'''
class ProjectFeatures(models.Model):
    project = models.OneToOneField(Project, on_delete=models.CASCADE, primary_key=True)
    has_contributing = models.BooleanField()
    has_readme = models.BooleanField()

    class Meta:
        verbose_name_plural = "Projects Features"

    def __str__(self):
        return self.project

    def __unicode__(self):
        return self.project

'''
    A project's timeSeries tells much about what happened to the repository in a given day.
    It's largely used for charts construction and data analysis.
    It's linked by an on_to_one relation to the Project model
'''
class TimeSeries(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    data_type = models.TextField()
    count = models.IntegerField()
    date = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Projects Time Series"

    def __str__(self):
        return self.project

    def __unicode__(self):
        return self.project

source/website/views.py
# -*- coding: utf-8 -*-
'''
    The views.py is responsible for handling with web requests
    and responses. The responses in our website
    usually are HTML pages containing data.
'''
from collections import Counter, OrderedDict
from django.shortcuts import render, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import Http404
from website.models import Project, ProjectStatistics, ProjectFeatures, TimeSeries

def index(request):
    '''
        The index method is responsible for
        handling index page requests.
        The values used in index.html are transmitted
        using the context variable.
    '''
    context = {
        'licenses': Project.objects.values_list('software_license', flat=True).distinct(),
        'languages': Project.objects.values_list('main_language', flat=True).distinct(),
        'domains': Project.objects.values_list('application_domain', flat=True).distinct(),
        }

    return render(request, 'website/index.html', context)

def explore(request):
    context = {}
    return render(request, 'website/explore.html', context)

def overview(request):
    context = {
        'projects_per_domain': OrderedDict(Counter(Project.objects.values_list('application_domain', flat=True)).most_common()),
        'projects_per_license': OrderedDict(Counter(Project.objects.values_list('software_license', flat=True)).most_common()),
        'projects_per_age': dict(Counter(Project.objects.values_list('age', flat=True)))
        }

    return render(request, 'website/overview.html', context)

def search(request):
    '''
        The search method is responsible for
        handling requests of the search field and the explore section.
        When a request is done, the requested parameters are filtered
        in the database.
    '''
    page = request.GET.get('page')
    query = request.GET.get('query')
    languages = request.GET.getlist('language')
    domains = request.GET.getlist('domain')
    licenses = request.GET.getlist('license')
    projects = Project.objects.all()

    if query:
        projects = projects.filter(name__contains=query)
    
    if languages:
        projects = projects.filter(main_language__in=languages)

    if domains:
        projects = projects.filter(application_domain__in=domains)

    if licenses:
        projects = projects.filter(software_license__in=licenses)

    paginator = Paginator(projects, 10)
    projects_list = paginator.get_page(page)

    context = {
        'projects_list': projects_list
        }

    return render(request, 'website/search.html', context)

def project(request, owner, name):
    '''
        The project method is responsible for
        handling projects requests. The values used in
        project.html are transmitted using the context variable.
    '''
    try:
        requested_project = Project.objects.get(name=name, owner=owner)

        context = {
            'project': requested_project,
            'newcomers_time_series': TimeSeries.objects.filter(project=requested_project.id, data_type='newcomers'),
            'project_statistics': ProjectStatistics.objects.get(project=requested_project.id),
            'project_features': ProjectStatistics.objects.get(project=requested_project.id)
            }
        return render(request, 'website/project.html', context)
    except Project.DoesNotExist:
        raise Http404('Project does not exist')
    except Project.MultipleObjectsReturned:
        raise Http404('Project does not exist')

def handler404(request):
    '''
        The handler404 method is responsible for
        handling exceptions. A clear example
        is the "DoesNotExist" exception.
    '''
    return render(request, 'website/error404.html', status=404)

source/website/templates/website/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="author" content="Open Universe Organization">
		<meta name="description" content="Promoting open source communities everyday.">
		<meta name="keywords" content="opensource,software,communities,newcomers">
		<!-- Title -->
		<title>
			{% block title %} Open Universe {% endblock %}
		</title>
		<!-- CSS -->
		<link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'css/libs/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
		<link href="{% static 'css/libs/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css">

		{% block css %} 
		<!-- Empty space for custom css --> 
		{% endblock %}

		<!-- Favicon -->
		<link rel="icon" href="{% static 'img/neptune.png' %}">
		<!-- Fonts -->
	</head>
	<body>
		<!-- Navbar -->
		<nav class="navbar navbar-fixed-top navbar-expand-lg navbar-light">
			<div class="container navbar-container">
				<!-- Brand -->
				<a href="{% url 'website:index' %}" class="navbar-brand">
					<span class="navbar-title align-middle">OPEN UNIVERSE</span>
					<img class="navbar-logo align-middle" src="{% static 'img/neptune.png' %}" alt="Made by Eucalpy"/>
				</a>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" 
				aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarToggler">					
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<!-- Overview -->
							<a class="nav-link" href="{% url 'website:overview' %}">Overview</a>
						</li>
						<li class="nav-item">
							<!-- Explore -->
							<a class="nav-link"  href="{% url 'website:explore' %}">Explore</a>
						</li>
						<li class="nav-item">
							<!-- Submit -->
							<a class="nav-link" href="https://github.com/openuniverseorg/openuniverse" target="__blank">Submit Project</a>
						</li>

						<li class="nav-item">
							<!-- Search -->
							<form class="navbar-form nav-link"  id="searchform" action="{% url 'website:search' %}" method="get" accept-charset="utf-8">
								<div class="input-group">
									<input type="text" name="query" class="search form-control" placeholder="Search for a project" id="search">
								</div>
							</form>	
						</li>
						<li class="nav-item">
							<!-- Contribute -->
							<a class="nav-link" href="https://github.com/openuniverseorg/openuniverse/wiki" target="__blank">Contribute</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
			
		<div class="content">
			{% block body %} 
			<!-- Empty space for body -->
			{% endblock %}
		</div>
			
		<!-- Footer -->
		<footer class="footer">
			<div class="container">
			</div>
		</footer>

		<!-- Javascript -->
		<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
		<script src="{% static 'js/libs/jquery.min.js' %}"></script>
		<script src="{% static 'js/libs/popper.min.js' %}"></script>
		<script src="{% static 'js/libs/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/libs/bootstrap-select.min.js' %}"></script>
		{% block javascript %}

		 <!-- Empty space for custom javascript --> 
		 {% endblock %}
		 
	</body>	
</html>

source/website/templates/website/error404.html
{% extends 'website/base.html' %}
{% load staticfiles %}
{% block title %} 404 - Page not found! {% endblock %}

{% block body %}
<h1>Page not found!</h1>    
{% endblock %}

source/website/templates/website/explore.html
<!-- Template -->
{% extends 'website/base.html' %}
{% load staticfiles %}
<!-- Title -->
{% block title %} Open Universe - Explore {% endblock %}
<!-- CSS -->
{% block css %}
<link href="{% static 'css/explore.css' %}" rel="stylesheet" type="text/css">
{% endblock  %}

{% block body %}
		<div class="jumbotron jumbotron-fluid">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
					</div>
				</div>
			</div>
		</div>
{% endblock %}

source/website/templates/website/index.html
<!-- Template -->
{% extends 'website/base.html' %}
{% load staticfiles %}
<!-- Title -->
{% block title %} Open Universe - Promoting open source communities {% endblock %}
<!-- CSS -->
{% block css  %}
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
{% endblock  %}

{% block body %}
		<div class="jumbotron jumbotron-fluid">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="introduction">
							<h1>
								<b>Created for newcomers</b>
							</h1>
							<h2>Designed for communities</h2>
							<p class="lead">Open Universe is an analysis platform designed to help new contributors find open source projects. Give yourself the opportunity to join this universe!</p>			
						</div>
					</div>
					<div class="col-lg-6">
						<form class="form">
							<h3>Find a new project</h3>
							<hr>
							<div class="form-group">
								<select class="select selectpicker" data-width="100%" title="Language">
									{% for language in languages %}
									<option>{{ language }}</option>
									{% endfor %}
								</select>
							</div>
							<div class="form-group">
									<select class="select selectpicker" data-width="100%" title="Domain">
										{% for domain in domains %}
										<option>{{ domain }}</option>
										{% endfor %}
									</select>
							</div>
							<div class="form-group">
									<select class="select selectpicker" data-width="100%" title="License">
										{% for license in licenses %}
										<option>{{ license }}</option>
										{% endfor %}
									</select>
							</div>	
							<button type="submit" class="btn find-btn">I'm ready</button>
						</form>
					</div>				
				</div>
			</div>
		</div>
		<div class="container text-justify">
		<div class="row">
			<div class="col-md-6">
				<span class="section-title">Abstract</span>
				<p>Developers are often interested in joining open source communities based on a set of motivations. Our mission
				is to provide the connection between open source projects who desire new contributors and interested developers
				who want to contribute.</p>
				<p>The analysis proposed in this website are based on <i>Wiese et. al methodology</i>,
				who tryed to comprehend how projects receptivity can be defined in open source projects, taking into consideration
				a group of metrics (e.g. programming languages and software license). The analysis proposed in our platform does not necessarly
				represent the real projects receptivity, but might be a good start point for newcomers to find interested open source projects.
				We encourage you to explore the {{ projects.count }} projects available in our platform! </p>
			</div>
		</div>
	</div>
{% endblock %}

source/website/templates/website/overview.html
<!-- Template -->
{% extends 'website/base.html' %}
{% load staticfiles %}
<!-- Title -->
{% block title %} Open Universe - Overview {% endblock %}
<!-- CSS -->
{% block css  %}
	<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css">
{% endblock  %}

{% block body %}
	<div class="container text-justify">
		<div class="row">
			<div class="col-md-12">
				<span class="section-title">Dataset</span>
				<div class="row">
					<div class="item col-md-6">
						<span class="item-title">DOMAIN</span>
						<div id="projects_per_domain"></div>
					</div>
					<div class="item col-md-6">
						<span class="item-title">AGE</span>
						<div id="projects_per_age"></div>
					</div>	
					<div class="item col-md-6">
						<span class="item-title">LICENSE</span>
						<div id="projects_per_license"></div>
					</div>	
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascript %}
<!-- Number of projects by domain -->
<script type="text/javascript">
	google.charts.load("current", { packages: ["corechart", "bar"]});
	google.charts.setOnLoadCallback(domainColumnChart);

	function domainColumnChart() {
		var data = new google.visualization.DataTable();
		data.addColumn('string','Domain');
		data.addColumn('number','Ocurrences');
		data.addColumn({type: 'string', role: 'style'});
		data.addRows([{% for domain, value in projects_per_domain.items %}["{{ domain }}", {{ value }}, 'color: #0057e7'], {% endfor %}]);

	  var options = {
		fontName: 'Helvetica',
		legend: { position: "none" },
		backgroundColor: 'transparent',
	    vAxis: {
	      title: "Ocurrences"
	    },
	    hAxis: {title: "Application Domain"}
	   };

	  var chart = new google.visualization.ColumnChart(
	    document.getElementById("projects_per_domain")
	  );

	  chart.draw(data, options);
	}
</script>

<!-- Number of projects by license -->
<script type="text/javascript">
	google.charts.load("current", { packages: ["corechart", "bar"]});
	google.charts.setOnLoadCallback(licenseColumnChart);

	function licenseColumnChart() {
		var data = new google.visualization.DataTable();
		data.addColumn('string','License');
		data.addColumn('number','Ocurrences');
		data.addColumn({type: 'string', role: 'style'});
		data.addRows([{% for license, value in projects_per_license.items %}["{{ license }}", {{ value }}, 'color: #008744'], {% endfor %}]);

	  var options = {
		fontName: 'Helvetica',
		legend: { position: "none" },
		backgroundColor: 'transparent',
	    vAxis: {
	      title: "Ocurrences"
	    },
	    hAxis: {title: "Software License"}
	   };

	  var chart = new google.visualization.ColumnChart(
	    document.getElementById("projects_per_license")
	  );

	  chart.draw(data, options);
	}
</script>

<!-- Number of projects by age -->
<script type="text/javascript">
	google.charts.load("current", { packages: ["corechart", "bar"]});
	google.charts.setOnLoadCallback(ageColumnChart);

	function ageColumnChart() {
		var data = new google.visualization.DataTable();
		data.addColumn('string','Age');
		data.addColumn('number','Ocurrence');
		data.addColumn({type: 'string', role: 'style'});
		data.addRows([{% for age, value in projects_per_age.items %}["{{ age }}", {{ value }}, 'color: #d62d20'], {% endfor %}]);

	  var options = {
		fontName: 'Helvetica',
		legend: { position: "none" },
		backgroundColor: 'transparent',
	    vAxis: {
	      title: "Ocurrences"
	    },
	    hAxis: {title: "Age (Years)"}
	   };

	  var chart = new google.visualization.ColumnChart(
	    document.getElementById("projects_per_age")
	  );

	  chart.draw(data, options);
	}
</script>
{% endblock %}

source/website/templates/website/project.html
<!-- Template -->
{% extends 'website/base.html' %}
<!-- Django -->
{% load staticfiles %}
{% load mathfilters %}
<!-- Title -->
{% block title %} {{project.name}} {% endblock %}
<!-- CSS -->
{%  block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
{%endblock%}

{% block body %}
<div class="container">
	<div class="row header">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12">
					<a href="{{project.github_url}}">
						<span class="project-name">{{ project.owner | capfirst }} / {{ project.name | capfirst }}</span>
					</a>
				</div>
			</div>	
			
			<div class="row description">
				<div class="col-md-3 text-center">
					<span class="description-item">
						<i class="fas fa-bullseye"></i>
						{{ project.application_domain }}
					</span>
				</div>
				<div class="col-md-3 text-center">
					<span class="description-item">
						<i class="fas fa-code"></i>
						{{ project.main_language }}
					</span>
				</div>
				<div class="col-md-3 text-center">
					<span class="description-item">
						<i class="fas fa-balance-scale"></i>
						{{ project.software_license }}
					</span>
				</div>
				<div class="col-md-3 text-center">
					<span class="description-item">
						<i class="far fa-clock"></i>
						{{ project.age }} year(s) of existence
					</span>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row section time-series">
		<div class="col-md-12">
			<div class="section-header row">
				<div class="col-md-12">
					<span class="section-header-title">Time Series</span>
				</div>
			</div>
			<div class="row section-chart">
				<div class="col-md-12">
					<span class="section-chart-title">Newcomers:</span>
					<div name="time-series" id="newcomers_{{ project.id }}"></div>
				</div>
			</div>
			<div class="row section-chart">
				<div class="col-md-12">
					<span class="section-chart-title">Forks:</span>
					<div name="time-series" id=""></div>
				</div>
			</div>
			<div class="row section-chart">
				<div class="col-md-12">
					<span class="section-chart-title">Pull-requests (Merged):</span>
					<div name="time-series" id=""></div>
				</div>
			</div>			
		</div>
	</div>
</div>
{% endblock %}

{% block javascript %}
<script>
	google.charts.load('current', {'packages':['annotationchart']});
	google.charts.setOnLoadCallback(drawNewcomersTimeSeries);
	
	function drawNewcomersTimeSeries(){
		var data = new google.visualization.DataTable();
		data.addColumn('datetime', 'Date');
		data.addColumn('number', 'Newcomers');
		data.addRows([{% for value in newcomers_time_series %}[new Date({{ value.date | date:"Y, m, d" }}), {{ value.count }}], {% endfor %}]);
		
		var options = {
			fontName: 'Rajdhani',
			displayAnnotations: true,
			title:'Newcomers (Daily)',
			hAxis: {
				title: 'Number of newcomers',
			},
			vAxis: {
				title: 'Date',
				logScale: false,
			},
			height:300
		};
		
		var newcomers_{{ project.id }} = new google.visualization.AnnotationChart(document.getElementById('newcomers_{{ project.id }}'));		
		newcomers_{{ project.id }}.draw(data, options);
	};	
</script>
{% endblock %}

source/website/templates/website/search.html
<!-- Template -->
{% extends 'website/base.html' %}
{% load staticfiles %}
{% load pagination %}
<!-- Title -->
{% block title %} Open Universe - Search {% endblock %}
<!-- CSS -->
{% block css %}
<link href="{% static 'css/search.css' %}" rel="stylesheet" type="text/css">
{% endblock  %}

{% block body %}
	<div class="container">
		<div class="list-group">
			<div class="list-header">
				<span class="list-title">PROJECTS</span>
			</div>
			{% for project in projects_list %}
				<a href="{% url 'website:project' project.owner project.name %}" class="list-group-item">
					<div class="row">
						<div class="col-md-6">
							<span class="list-group-item-title">{{ project.name | capfirst }}</span><br>
							<span class="list-group-item-subtitle">Owned by {{ project.owner | capfirst }}</span> <br>
							<span class="list-group-item-subtitle">License: {{ project.software_license }}</span>
						</div>
					</div>
				</a>
			{% endfor %}

			<nav>
				<ul class="pagination">
					{% if projects_list.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?{% replace_parameter request 'page' projects_list.previous_page_number %}"">
							<span aria-hidden="true">&laquo;</span>
						</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?{% replace_parameter request 'page' projects_list.previous_page_number %}"">
							<span>{{ projects_list.previous_page_number }}</span>
						</a>
					</li>
					{% endif %}
					
					<li class="page-item active">
						<a class="page-link" href="#">{{ projects_list.number }}</a>
					</li>
					
					{% if projects_list.has_next %}
					<li class="page-item">
						<a class="page-link" href="?{% replace_parameter request 'page' projects_list.next_page_number %}">
							<span>{{ projects_list.next_page_number }}</span>
						</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?{% replace_parameter request 'page' projects_list.next_page_number %}">
							<span aria-hidden="true">&raquo;</span>
						</a>
					</li>
					{% endif %}
				</ul>
			</nav>
		</div>
	</div>
{% endblock %}